import javax.swing.JOptionPane;

public class ReturnForm extends javax.swing.JFrame {

    /**
     * Creates new form ReturnForm
     */
    public ReturnForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblClientName = new javax.swing.JLabel();
        txtClientName = new javax.swing.JTextField();
        lblVehicleType = new javax.swing.JLabel();
        lblVehicleModel = new javax.swing.JLabel();
        lblDateUse = new javax.swing.JLabel();
        lblReturnDate = new javax.swing.JLabel();
        lblVehicleDamaged = new javax.swing.JLabel();
        lblPenalty = new javax.swing.JLabel();
        txtVehicleType = new javax.swing.JTextField();
        txtVehicleModel = new javax.swing.JTextField();
        txtDateUse = new javax.swing.JTextField();
        txtReturnDate = new javax.swing.JTextField();
        txtPenalty = new javax.swing.JTextField();
        chkDamage = new javax.swing.JCheckBox();
        btnCalculatePenalty = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vehicle Return Form");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 529, 34));

        lblClientName.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblClientName.setText("Client Name:");
        jPanel1.add(lblClientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 46, 113, 28));

        txtClientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClientNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtClientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 50, 358, -1));

        lblVehicleType.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblVehicleType.setText("Vehicle Type:");
        jPanel1.add(lblVehicleType, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 86, 113, 28));

        lblVehicleModel.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblVehicleModel.setText("Vehicle Model:");
        jPanel1.add(lblVehicleModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 126, 113, 28));

        lblDateUse.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblDateUse.setText("Date Use:");
        jPanel1.add(lblDateUse, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 166, 113, 28));

        lblReturnDate.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblReturnDate.setText("Return Date:");
        jPanel1.add(lblReturnDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 206, 113, 28));

        lblVehicleDamaged.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblVehicleDamaged.setText("Vehicle Damaged:");
        jPanel1.add(lblVehicleDamaged, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 246, -1, 28));

        lblPenalty.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblPenalty.setText("Penalty(If Damaged):");
        jPanel1.add(lblPenalty, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 286, 135, 28));
        jPanel1.add(txtVehicleType, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 90, 358, -1));

        txtVehicleModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehicleModelActionPerformed(evt);
            }
        });
        jPanel1.add(txtVehicleModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 130, 358, -1));

        txtDateUse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateUseActionPerformed(evt);
            }
        });
        jPanel1.add(txtDateUse, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 170, 358, -1));

        txtReturnDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReturnDateActionPerformed(evt);
            }
        });
        jPanel1.add(txtReturnDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 206, 358, -1));
        jPanel1.add(txtPenalty, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 290, 336, -1));

        chkDamage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDamageActionPerformed(evt);
            }
        });
        jPanel1.add(chkDamage, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 246, 85, 28));

        btnCalculatePenalty.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCalculatePenalty.setText("Calculate Penalty");
        btnCalculatePenalty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculatePenaltyActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalculatePenalty, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 174, 47));

        btnSubmit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 186, 47));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtClientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClientNameActionPerformed

    private void txtVehicleModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehicleModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicleModelActionPerformed

    private void txtDateUseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateUseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateUseActionPerformed

    private void txtReturnDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReturnDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReturnDateActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void chkDamageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDamageActionPerformed

    }//GEN-LAST:event_chkDamageActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        String clientName = txtClientName.getText();
        String vehicleType = txtVehicleType.getText();
        String vehicleModel = txtVehicleModel.getText();
        String dateUse = txtDateUse.getText();
        String returnDate = txtReturnDate.getText();
        boolean isDamaged = chkDamage.isSelected();
        String penalty = txtPenalty.getText();

        String message = String.format(
            "Client Name: %s\nVehicle Type: %s\nVehicle Model: %s\nDate of Use: %s\nReturn Date: %s\nDamaged: %s\nPenalty: %s",
            clientName, vehicleType, vehicleModel, dateUse, returnDate, isDamaged ? "Yes" : "No", penalty
        );

        JOptionPane.showMessageDialog(this, message, "Return Summary", JOptionPane.INFORMATION_MESSAGE);
        resetForm();
    }

    private void resetForm() {
        txtClientName.setText("");
        txtVehicleType.setText("");
        txtVehicleModel.setText("");
        txtDateUse.setText("");
        txtReturnDate.setText("");
        chkDamage.setSelected(false);
        txtPenalty.setText("");
    
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnCalculatePenaltyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculatePenaltyActionPerformed
        if (chkDamage.isSelected()) {
            txtPenalty.setText("₱500");
        } else {
            txtPenalty.setText("₱0");
        }
    }//GEN-LAST:event_btnCalculatePenaltyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculatePenalty;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JCheckBox chkDamage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lblClientName;
    private javax.swing.JLabel lblDateUse;
    private javax.swing.JLabel lblPenalty;
    private javax.swing.JLabel lblReturnDate;
    private javax.swing.JLabel lblVehicleDamaged;
    private javax.swing.JLabel lblVehicleModel;
    private javax.swing.JLabel lblVehicleType;
    private javax.swing.JTextField txtClientName;
    private javax.swing.JTextField txtDateUse;
    private javax.swing.JTextField txtPenalty;
    private javax.swing.JTextField txtReturnDate;
    private javax.swing.JTextField txtVehicleModel;
    private javax.swing.JTextField txtVehicleType;
    // End of variables declaration//GEN-END:variables
}
